In [1]:
import torch
from transformers import BertTokenizerFast,XLMRobertaTokenizer
import string
import torch.nn as nn
from transformers import BertPreTrainedModel, BertModel, BertTokenizerFast
from transformers import RobertaPreTrainedModel,XLMRobertaConfig, XLMRobertaTokenizer, XLMRobertaModel

In [2]:
tok2 = BertTokenizerFast.from_pretrained("bert-base-multilingual-cased")
tok = XLMRobertaTokenizer.from_pretrained("xlm-roberta-large")
#bert = BertModel.from_pretrained('bert-base-uncased')

In [27]:
class BERTmodel(nn.Module):
    def __init__(self,
                 bert,
                 output_dim):
        
        super().__init__()
        
        self.bert = bert
        #embedding_dim = bert.config.to_dict()['hidden_size']
        
    def forward(self, text):
        embedded = self.bert(text)[1]
        return embedded

In [44]:
bert = BertModel.from_pretrained('bert-base-multilingual-cased')

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
import torch
from transformers import BertTokenizer, BertForMaskedLM

text = "[CLS] Many people climb this mountain during the summer every year. [SEP]"

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
words = tokenizer.tokenize(text)
print(words)

# 予測する単語を[MASK]に変換する
# 今回は[during]を予測するため、6番目を変換
msk_idx = 6
words[msk_idx] = "why"
#print(tokenizer.convert_tokens_to_ids("[unused1]"))
print(words)

# tokenをidに変換する
word_ids = tokenizer.convert_tokens_to_ids(words)
word_tensor = torch.tensor([word_ids])
print(word_tensor)

msk_model = BertForMaskedLM.from_pretrained("bert-base-uncased")

msk_model.eval()

x = word_tensor
y = msk_model(x)
result = y[0]
print(result.size())

_, msk_ids = torch.topk(result[0][msk_idx], k=5)
result_words = tokenizer.convert_ids_to_tokens(msk_ids.tolist())

print(result_words)


['[CLS]', 'many', 'people', 'climb', 'this', 'mountain', 'during', 'the', 'summer', 'every', 'year', '.', '[SEP]']
['[CLS]', 'many', 'people', 'climb', 'this', 'mountain', 'why', 'the', 'summer', 'every', 'year', '.', '[SEP]']
tensor([[ 101, 2116, 2111, 7105, 2023, 3137, 2339, 1996, 2621, 2296, 2095, 1012,
          102]])


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([1, 13, 30522])
['in', 'during', 'on', 'for', 'over']


In [3]:
print(tokenizer.convert_tokens_to_ids("[unused1]"))
print(tokenizer.convert_tokens_to_ids("[MASK]"))

2
103


In [ ]:
['[CLS]', 'many', 'people', 'climb', 'this', 'mountain', 'during', 'the', 'summer', 'every', 'year', '.', '[SEP]']
['[CLS]', 'many', 'people', 'climb', 'this', 'mountain', 'in', 'the', 'summer', 'every', 'year', '.', '[SEP]']

In [4]:
#torch.Size([1, 13, 30522])
#['in', 'during', 'throughout', 'over', 'for']
tok.add_tokens(['[Q]'])
tok.add_tokens(['[D]'])
tok.add_tokens(['[zho]'])
tok.add_tokens(['[fas]'])
tok.add_tokens(['[rus]'])
tok.convert_ids_to_tokens(a)

['<s>',
 '▁[',
 'Q',
 '][',
 'z',
 'ho',
 ']',
 'what',
 '▁is',
 '▁hus',
 'ky',
 '▁size',
 '▁boys',
 '</s>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>',
 '<mask>']

In [3]:
a = [     0,    378,   2737,  29839,    169,    497,    268, 124409,     83,
           8675,   1002,  13267, 115982,      2, 250001, 250001, 250001, 250001,
         250001, 250001, 250001, 250001, 250001, 250001, 250001, 250001, 250001,
         250001, 250001, 250001, 250001, 250001]

In [ ]:
Q_marker_token, Q_marker_token_id = '[Q]',250003

In [44]:
batch_text = ['[zho]私は猫か？']
batch_text = ['[Q]' + x for x in batch_text]
ids = tok(batch_text,padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)["input_ids"]

print(ids)
print(ids,tok.convert_ids_to_tokens(ids[0]))

tensor([[     0, 250003, 250002,  65579,  35076,   1894,     32,      2,      1,
              1,      1,      1,      1,      1,      1]])
tensor([[     0, 250003, 250002,  65579,  35076,   1894,     32,      2,      1,
              1,      1,      1,      1,      1,      1]]) ['<s>', '[Q]', '[zho]', '▁私は', '猫', 'か', '?', '</s>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>', '<pad>']


In [14]:
batch_text = ['私は猫か？']
batch_text2 = ['私は猫か？']
ids = tok(batch_text,padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)['input_ids']
mask = tok(batch_text,padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)['attention_mask']

ids2 = tok2(batch_text2,padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)['input_ids']
mask = tok2(batch_text2,padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)['attention_mask']
print(ids,ids2)

Qids[:, 1] = 250003
ids[:, 2] = 250002
Qids[Qids == 1] = tok.mask_token_id



tensor([[    0, 65579, 35076,  1894,    32,     2,     1,     1,     1,     1,
             1,     1,     1,     1,     1]]) tensor([[  101,  5949,  1947,  5453,  1911, 10083,   102,     0,     0,     0,
             0,     0,     0,     0,     0]])


In [10]:
batch_text2 = ['私は[PAD]か？']
batch_text = ['私は<mask>か？']
ids = tok(batch_text,padding='max_length', truncation=True,
                return_tensors='pt', max_length=30)['input_ids']

ids2 = tok2(batch_text2,padding='max_length', truncation=True,
                return_tensors='pt', max_length=30)['input_ids']

#ids[ids == 0] = tok.mask_token_id
#ids2[ids2 == 0] = tok2.mask_token_id

mask = tok(batch_text,padding='max_length', truncation=True,
                return_tensors='pt', max_length=30)['attention_mask']

mask2 = tok2(batch_text2,padding='max_length', truncation=True,
                return_tensors='pt', max_length=30)['attention_mask']
print(ids,mask)
print(ids2,mask2)
print(tok.convert_ids_to_tokens(250001))

tensor([[     0,  65579, 250001,      6,   1894,     32,      2,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1]]) tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]])
tensor([[  101,  5949,  1947,     0,  1911, 10083,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]]) tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]])
<mask>


In [19]:
torch.set_printoptions(edgeitems=1000)

In [22]:
emb = bert(ids,mask)
emb = emb.last_hidden_state[2]
emb[3]

IndexError: index out of range in self

In [4]:
tok3 = BertTokenizerFast.from_pretrained("bert-base-uncased")

[1, 30, 768]
1個の文章を30でpaddingしたmBERT　768次元のベクトルが出力


In [6]:
for i in range(15):
    print(tok.convert_ids_to_tokens(i),tok2.convert_ids_to_tokens(i))

<s> [PAD]
<pad> [unused1]
</s> [unused2]
<unk> [unused3]
, [unused4]
. [unused5]
▁ [unused6]
s [unused7]
▁de [unused8]
- [unused9]
▁a [unused10]
a [unused11]
: [unused12]
e [unused13]
i [unused14]


In [62]:
print(tok.convert_tokens_to_ids("[unused1]"))
print(tok.convert_tokens_to_ids("[unused2]"))

3
3


In [63]:
tok = XLMRobertaTokenizer.from_pretrained("xlm-roberta-large")
tok.add_tokens(['[unused1]'])
tok.add_tokens(['[unused2]'])
tok.add_tokens(['[unused_zho]'])
tok.add_tokens(['[unused_fas]'])
tok.add_tokens(['[unused_rus]'])

1

In [4]:
batch_text = ['私は[MASK]か？']

In [5]:
Qids = tok(batch_text)['input_ids']
batch_text = ['. ' + x for x in batch_text]
obj = tok(batch_text, padding='max_length', truncation=True,
                return_tensors='pt', max_length=30)
Qids,Qmask = obj['input_ids'], obj['attention_mask']
Qids[:, 1] = 250003
ids[:, 2] = 250002
Qids[Qids == 1] = tok.mask_token_id
print(obj)



{'input_ids': tensor([[     0, 250003,      5,  65579,   1065,  40639,    605,    268,   1894,
             32,      2, 250001, 250001, 250001, 250001, 250001, 250001, 250001,
         250001, 250001, 250001, 250001, 250001, 250001, 250001, 250001, 250001,
         250001, 250001, 250001]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]])}


In [26]:
batch_text = ['私は[MASK]か？']
text = tok2(batch_text,padding='max_length', truncation=True,
                return_tensors='pt', max_length=30)
a = a['input_ids']
print(a)
for ids in a:
    print(tok2.convert_ids_to_tokens(ids))

{'input_ids': tensor([[  101,  1904, 27843, 11588,  1881,   103,  1956,  7069, 20832, 15752,
         10083,   102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1904, 27843, 11588,  1881,     0,  1956,  7069, 20832, 15752,
         10083,   102,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [  101, 11065, 10301,   169, 41163,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0

In [68]:
batch_text = ["I like a cat", "I am a student","You are a cat"]
Qids = tok(batch_text)['input_ids']
batch_text = ['. ' + x for x in batch_text]
obj = tok(batch_text, padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)
Qids,mask = obj['input_ids'], obj['attention_mask']
print(mask.indices)
indices = mask.sum(-1).sort()#.indices
print(indices)
#reverse_indices = indices.sort().indices
#print(reverse_indices)

<built-in method indices of Tensor object at 0x7f6e10141890>
torch.return_types.sort(
values=tensor([8, 8, 8]),
indices=tensor([0, 1, 2]))


In [23]:
Dids = tok(batch_text2)['input_ids']
batch_text2 = ['. ' + x for x in batch_text2]
obj = tok(batch_text2, padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)
Dids,Dmask = obj['input_ids'], obj['attention_mask']
Dids[:, 1] = 250002
#ids[:, 2] = 250002
Dids[Dids == 1] = tok.mask_token_id
print(ids,obj['attention_mask'])

NameError: name 'batch_text2' is not defined

In [41]:
N = len(batch_text)
print(Dids)
Dids, Dmask = Dids.view(2, N, -1), Dmask.view(2, N, -1)

tensor([[     0, 250002,      5,     87,   1884,     10,   7515,      2, 250001,
         250001, 250001, 250001, 250001, 250001, 250001],
        [     0, 250002,      5,     87,    444,     10,   9836,      2, 250001,
         250001, 250001, 250001, 250001, 250001, 250001],
        [     0, 250002,      5,   2583,    621,     10,   7515,      2, 250001,
         250001, 250001, 250001, 250001, 250001, 250001]])


RuntimeError: shape '[2, 3, -1]' is invalid for input of size 45

250001
<mask>
250001
250004


In [56]:
for i in range(110):
    print(tok.convert_ids_to_tokens(i),tok2.convert_ids_to_tokens(i))

<s> [PAD]
<pad> [unused1]
</s> [unused2]
<unk> [unused3]
, [unused4]
. [unused5]
▁ [unused6]
s [unused7]
▁de [unused8]
- [unused9]
▁a [unused10]
a [unused11]
: [unused12]
e [unused13]
i [unused14]
▁( [unused15]
) [unused16]
▁i [unused17]
t [unused18]
n [unused19]
▁- [unused20]
▁la [unused21]
▁en [unused22]
▁in [unused23]
▁na [unused24]
' [unused25]
’ [unused26]
... [unused27]
▁e [unused28]
▁на [unused29]
。 [unused30]
o [unused31]
? [unused32]
en [unused33]
u [unused34]
▁и [unused35]
▁o [unused36]
、 [unused37]
! [unused38]
m [unused39]
▁se [unused40]
▁que [unused41]
r [unused42]
的 [unused43]
▁" [unused44]
▁di [unused45]
▁– [unused46]
▁to [unused47]
▁da [unused48]
▁в [unused49]
، [unused50]
▁un [unused51]
▁“ [unused52]
y [unused53]
▁do [unused54]
▁je [unused55]
er [unused56]
▁sa [unused57]
" [unused58]
а [unused59]
▁og [unused60]
▁за [unused61]
▁A [unused62]
” [unused63]
/ [unused64]
▁و [unused65]
an [unused66]
te [unused67]
▁die [unused68]
▁да [unused69]
▁the [unused70]
d [unused71]
▁er

In [58]:
batch_text = ['.' + x for x in batch_text]

In [59]:
obj = tok(batch_text, padding='max_length', truncation=True,
                return_tensors='pt', max_length=15)
ids, mask = obj['input_ids'], obj['attention_mask']
print(ids)
ids[:, 1] = 250002
#ids[ids == 0] = tok.mask_token_id
print(ids)

tensor([[   0,    6,    5,  568, 1884,   10, 7515,    2,    1,    1,    1,    1,
            1,    1,    1],
        [   0,    6,    5,  568,  444,   10, 9836,    2,    1,    1,    1,    1,
            1,    1,    1]])
tensor([[     0, 250002,      5,    568,   1884,     10,   7515,      2,      1,
              1,      1,      1,      1,      1,      1],
        [     0, 250002,      5,    568,    444,     10,   9836,      2,      1,
              1,      1,      1,      1,      1,      1]])


In [7]:
tok.convert_ids_to_tokens(250000)

'稣'

In [25]:
tok.add_tokens(['[D]'])

1

In [26]:
tok("[D]", add_special_tokens=False)

{'input_ids': [250002], 'attention_mask': [1]}